server:
#  port: 80
#  本地测试端口
  port: 10521


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
#    username: ${MYSQL_USERNAME}
#    password: ${MySQL_PASSWORD}
#    本地测试
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: zhang1133..
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

wx:
  appId: wxc0016e0846645158
  secret: 9af77250671836e1316d0750dfcd2030
logging:
  file:
    name: toolApi.log

